### ISSUE TITLE
Empty documents being sent to Firehose

### ISSUE THREAD

**Issue by babaMar** [aws/amazon-kinesis-firehose-for-fluent-bit#143]
It looks like empty payloads are being sent to Firehose and in turn to Elasticsearch, only the `timestamp` field is populated by `fluentbit`:

```
{
  "_index": "log-2021-08-26",
  "_type": "_doc",
  "_id": "49621369204884914652732002225806045706578374688214351874.3",
  "_score": 1,
  "_source": {
    "timestamp": "2021-08-26T09:37:02.608335"
  },
  "fields": {
    "timestamp": [
      "2021-08-26T09:37:02.608Z"
    ]
  }
}
```

has anyone experienced something similar?
Any idea how I could thoroughly debug it, event with `FLB_LOG_LEVEL=debug` can't see much

**Comment by babaMar** [comment]
This is caused by log records for which no field can be parsed with `config-file-value: '/fluent-bit/configs/parse-json.conf'`. Seems a bit silly to deliver such records to Firehose IMHO

**Comment by hossain-rayhan** [comment]
Hi @babaMar, can you please explain a little bit and prvide an example of your log file? What was in your log record? Is it empty string or an invalid format?

Alos, can you please provide the full fluent-bit config and the image version you are using? Thanks.

**Comment by babaMar** [comment]
Hi @hossain-rayhan the container was streaming logs to `stdout` of the form:

`2021-08-26 14:53:51,967 [logger] [pipeline:80:__init__] INFO: Initiated pipeline [test_in->test_in] with processor: mock_processor _fails_for_single_dp`, together with already JSON-formatted record (the latter being correctly delivered to Firehose)

I'm using `amazon/aws-for-fluent-bit:latest` with:
```
FirelensConfiguration:
  Type: fluentbit
  Options:
    enable-ecs-log-metadata: 'true'
    config-file-type: 'file'
    config-file-value: '/fluent-bit/configs/parse-json.conf'
```

So basically those logs don't get parsed, which is fine, but I would expect `fluentbit` to discard records with no parsed fields

**Comment by zhonghui12** [comment]
Hi @babaMar,

Thanks for your detailed information but for now, we have no plan to fix this one as we are actively working on other priority tasks. Currently I will close this issue but please feel free to reopen it if you think it becomes a big issue to you.

Thanks.
