### ISSUE TITLE
Support sub-second time reporting

### ISSUE THREAD

**Issue by KyleMarMcTVG** [aws/amazon-kinesis-firehose-for-fluent-bit#26]
At present, the Time_Format parameter only supports strftime format strings, which do not provide a sub-second feature. This makes it impossible to properly order logs.

Fluent Bit [supports](https://docs.fluentbit.io/manual/v/1.1/parser#time-resolution-and-fractional-seconds) `%L`, which provides nanoseconds. Is this a feasible addition to this Firelens plugin?

**Comment by hencrice** [comment]
Related: https://github.com/aws/amazon-kinesis-streams-for-fluent-bit/issues/34

**Comment by hencrice** [comment]
This was released as part of AWS for Fluent Bit 2.6.0. Closing.
