### ISSUE TITLE
Add support for the Arm64 architecture

### ISSUE THREAD

**Issue by JeffUnderhill** [aws/amazon-kinesis-firehose-for-fluent-bit#52]
With the introduction of AWS Graviton2 we observe customer interest in https://github.com/aws/aws-for-fluent-bit which is in turn dependent on an Arm64 build of amazon-kinesis-firehose-for-fluent-bit to be available.

Here's the associated issue in aws-for-fluent-bit - https://github.com/aws/aws-for-fluent-bit/issues/44

**Comment by zhonghui12** [comment]
Hi @JeffUnderhill , ARM64 support has been released and you can check here for more details: https://github.com/aws/aws-for-fluent-bit/blob/mainline/CHANGELOG.md.

Thanks.
