### ISSUE TITLE
Handling duplicate records

### ISSUE THREAD

**Issue by karthikeayan** [aws/amazon-kinesis-firehose-for-fluent-bit#54]
When using aws-for-fluent-bit to send the records to Elasticsearch via Kinesis Firehose, I see duplicate records in Elasticsearch.

Every record appears twice.

Is this a known issue? Any work arounds for this? Blocked moving Firelens into Production with this.

**Comment by sonofachamp** [comment]
Can you provide more info about your setup and share your Fluent Bit configuration file minus sensitive information?

**Comment by karthikeayan** [comment]
Setup is pretty straight forward,

- Firelens container as sidecar in Fargate task definition
- Firelens sends the logs to Firehose using below configuration
- Firehose sends it to Elasticsearch (Firehose doesn't have "Source record transformation enabled"

I could see the logs in Cloudwatch as well as in Elasticsearch, however in Elasticsearch every record apperas twice, in Cloudwatch there are no duplicates.

fluent-bit.conf
```
[SERVICE]
    Flush 1
    Grace 30
    Log_Level debug
    Parsers_File parser.conf

[FILTER]
    Name parser
    Match *
    Key_Name log
    Parser springboot_parser
    Preserve_Key true
    Reserve_Data true

[FILTER]
    Name parser
    Match *
    Key_Name log
    Parser springboot1_parser
    Preserve_Key true
    Reserve_Data true

[FILTER]
    Name parser
    Match *
    Key_Name log
    Parser hibernate_parser
    Preserve_Key true
    Reserve_Data true

[FILTER]
    Name parser
    Match *
    Key_Name log_message
    Parser json
    Preserve_Key true
    Reserve_Data true

[OUTPUT]
    Name firehose
    Match  **
    region us-east-1
    delivery_stream accel-ms
    time_key timestamp
    time_key_format %Y-%m-%dT%H:%M:%S%z

[OUTPUT]
    Name cloudwatch
    Match **
    region us-east-1
    log_group_name /ecs/${MICROSERVICE_NAME}
    log_stream_prefix fluentbit.
    auto_create_group true
```

parser.conf
```
[PARSER]
    Name   springboot_parser
    Format regex
    Regex (?<date>[0-9]+-[0-9]+-[0-9]+\s+[0-9]+:[0-9]+:[0-9]+.[0-9]*)\s+(?<thread>\[.*?\])\s+(?<level>TRACE|DEBUG|INFO|WARN|ERROR\OFF)\s+(?<class>.*?)\s+-\s+(?<log_message>.*)
    Time_Keep On

[PARSER]
    Name   springboot1_parser
    Format regex
    Regex (?m-ix)(?<date>[0-9]+-[0-9]+-[0-9]+\s+[0-9]+:[0-9]+:[0-9]+.[0-9]*)\s+(?<level>TRACE|DEBUG|INFO|WARN|ERROR\OFF)\s+(?<const>.*?)\s+(?<dash>---)\s+(?<thread>\[.*\])\s+(?<class>.*?)\s+(?<logmessage>.*)
    Time_Keep On

[PARSER]
    Name   hibernate_parser
    Format regex
    Regex ^(?<const>Hibernate):\s+(?<query>.*)
    Time_Keep On

[PARSER]
    Name        json
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep   On
```

**Comment by sonofachamp** [comment]
Thanks for the info. I haven't been able to replicate this.

I have a few more clarifying questions:
* What version of the `aws-for-fluent-bit` image are you using?
* Are you able to identify where the duplication is occurring within your setup?
    * It seems it must be happening either between Fluent Bit processing -> Kinesis via this plugin or between Kinesis -> Elasticsearch
    * If duplication is occurring before either of those I'd expect to see the duplication in CloudWatch destination as well
* Is the duplication consistent (i.e. are all records always duplicated in the Elasticsearch destination?)

**Comment by karthikeayan** [comment]
> What version of the aws-for-fluent-bit image are you using?

amazon/aws-for-fluent-bit:2.3.0

> Are you able to identify where the duplication is occurring within your setup?

I don't see duplicates in Cloudwath. I am not an Firehose expert, I am using Firehose only because Firelens can't send the logs directly to AWS managed Elasticsearch(please correct me, if am wrong)

> Is the duplication consistent (i.e. are all records always duplicated in the Elasticsearch destination?)

Yes, it is consistent, I see duplicates always in Elasticsearch.

**Comment by karthikeayan** [comment]
Cloudwatch:
![Screen Shot 2020-08-05 at 1 36 50 PM](https://user-images.githubusercontent.com/5030782/89389393-f8b9af80-d722-11ea-937e-c883be911812.png)

Elasticsearch:
![Screen Shot 2020-08-05 at 1 37 06 PM](https://user-images.githubusercontent.com/5030782/89390053-d4aa9e00-d723-11ea-9731-47b0eb8c14cb.png)

I also tried with 2.6.1, issue persists.

Attaching the screenshots of Cloudwatch and Elasticsearch for more information. I see 226 entries in Cloudwatch, exactly double the number of records in Elasticsearch, which is 552.

**Comment by sonofachamp** [comment]
> I don't see duplicates in Cloudwath. I am not an Firehose expert, I am using Firehose only because Firelens can't send the logs directly to AWS managed Elasticsearch(please correct me, if am wrong)
> 
> >

In the [Fluent Bit v1.5.0](https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch) release Amazon Elasticsearch support was added to the [native Elasticsearch plugin](https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch), so you can use that to send to Amazon Elasticsearch directly and remove Firehose. This feature is available in `aws-for-fluent-bit` [`v2.4.0` or later](https://github.com/aws/aws-for-fluent-bit/releases).

**Comment by sonofachamp** [comment]
Hey @karthikeayan, have you been able to try the native Elasticsearch plugin instead of the Firehose plugin? I'm curious if you're still seeing duplication or if that issue went away for you after the swap.

**Comment by karthikeayan** [comment]
@sonofachamp yes, I just tried the native Elasticsearch plugin in my sandbox environment. I don't see the duplicates. Will be moving this to all my environments in the next few days. Do you think the issue am facing is related to the issue being discussed in this AWS Forums? 

https://forums.aws.amazon.com/thread.jspa?threadID=237104

**Comment by karthikeayan** [comment]
@sonofachamp 

It turns out to be the duplication issue is because of configuration issues from my side. I have firehose output configured in two places, thats why I see duplication in Elasticsearch.

1. ECS Task Definition, inside the firelens container logging driver configuration, I have this,
```
        "options": {
          "delivery_stream": "project-ms",
          "time_key_format": " %Y-%m-%dT%H:%M:%S%z",
          "region": "us-east-1",
          "Match": "**",
          "Name": "firehose",
          "time_key": "timestamp"
        }
```

2. In my custom fluentbit.conf file which is in /fluent-bit/etc/project-fluent-bit.conf on the container itself.

Once I remove the firehose output from custom configuration, I don't see duplicates any more.

I am still testing the Elasticsearch output plugin.

**Comment by sonofachamp** [comment]
Awesome, I'm glad you figured it out! Thanks for the update.
