### ISSUE TITLE
Truncate large log events

### ISSUE THREAD

**Issue by MeghnaPrabhu** [aws/amazon-kinesis-firehose-for-fluent-bit#58]
Currently, all log records that are greater than the max size are dropped. We should ideally truncate the JSON instead of discarding it so that the customers can see the partial log and identify why it is so large.

This issue needs to be fixed even on https://github.com/aws/amazon-kinesis-streams-for-fluent-bit

**Comment by PettitWesley** [comment]
This also needs to be fixed in the Core C AWS plugins as well.
