### ISSUE TITLE
Is this now deprecated in favour of the vanilla Firehose plugin?

### ISSUE THREAD

**Issue by pranavmarla** [aws/amazon-kinesis-firehose-for-fluent-bit#75]
I see that v1.6 of upstream/vanilla Fluent Bit now includes its own output plugin for writing to Firehose, and [says this](https://docs.fluentbit.io/manual/pipeline/outputs/firehose):

> This is the documentation for the core Fluent Bit Firehose plugin written in C. It can replace the aws/amazon-kinesis-firehose-for-fluent-bit Golang Fluent Bit plugin released last year.

However, I don't see any corresponding deprecation notice here. So, to clarify:
1. Is this Amazon-flavour Firehose plugin now deprecated?
2. If not, for new users who want to use Fluent Bit to send logs from EKS to Firehose, should we use: 
a) The Amazon-flavour Fluent Bit Docker image (containing this Amazon-flavour Firehose plugin)
OR
b) The vanilla Fluent Bit Docker image (containing the new vanilla Firehose plugin)

**Comment by PettitWesley** [comment]
Related: https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/issues/116

**Comment by PettitWesley** [comment]
I think the same answer will probably apply for the firehose plugins. Though getting feature parity in the core plugin would be easier for Firehose than for Cloudwatch.

**Comment by PettitWesley** [comment]
Action Item: Clarify this in a note in this repo's readme and in the core Fluent Bit documentation.

I think we should also print a statement when this plugin's code starts up reminding people to check out the new one and migrate if they can. 

We will keep this one around, but we do want people to migrate to the new/better plugin.

**Comment by zhonghui12** [comment]
A notice has been added in README: https://github.com/aws/amazon-kinesis-firehose-for-fluent-bit/pull/82. This issue will be closed.

**Comment by pranavmarla** [comment]
For future reference, linking [this comment](https://github.com/aws/amazon-kinesis-firehose-for-fluent-bit/pull/82#discussion_r527492461) by PettitWesley:

> Continuing to use the golang CloudWatch plugin is valid... it has some very useful features which the new core one lacks. However, for Firehose users, there is mostly not a good reason for them to continue to use this plugin. I think essentially all of them could migrate, the replace_dots option which is unique to this plugin is probably not widely used.

**Comment by PettitWesley** [comment]
Thanks.

I'm also actively working on [this feature request](https://github.com/aws/amazon-kinesis-firehose-for-fluent-bit/issues/12), but implementing it in the core plugin. The plugin in this repo will soon have a feature gap.
