### ISSUE TITLE
Consider adding a flunet-bit kinesis plugin as well.

### ISSUE THREAD

**Issue by rverma-nikiai** [aws/amazon-kinesis-firehose-for-fluent-bit#8]
If we are using logs as a source of events, we might want to push logs to kinesis.

**Comment by PettitWesley** [comment]
@rverma-nikiai We're planning to add a Kinesis Data Streams plugin soon!

**Comment by vgunapati** [comment]
@PettitWesley any update?

**Comment by PettitWesley** [comment]
@vgunapati We're working on it here: https://github.com/aws/amazon-kinesis-streams-for-fluent-bit

**Comment by PettitWesley** [comment]
@rverma-nikiai @vgunapati The plugin works; you can find the code in the repo above.

We'll have this released in the AWS for Fluent Bit image soon.

**Comment by PettitWesley** [comment]
Released in v2.0.0!
